About/urls.py
from django.contrib import admin

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from About import views


app_name = 'About'
urlpatterns = [
   
    path("about_us/", views.about_us, name='about_us'),
 
    path("team_info_form/", views.team_info_form, name='team_info_form'),
    path("edit_team_info/<int:member_id>", views.edit_team_info, name='edit_team_info'),
    path("delete_info/<int:member_id>", views.delete_info, name='delete_info'),
    # path("team_member_view/", views.team_member_view, name='team_member_view'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('my-posts/', views.my_blog_posts, name='my_blog_posts'),
    path('approval/', views.blog_approval_list, name='blog_approval_list'),
    path('approve/<int:pk>/', views.blog_approve, name='blog_approve'),
    path('like/<int:pk>/', views.like_blog_post, name='like_blog_post'),
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/edit/', views.blog_edit, name='blog_edit'),
    path('<slug:slug>/delete/', views.blog_delete, name='blog_delete'),
]

safenet_ai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('research/', include('research_papers.urls')),
    path('expert-topics/', include('expert_topics.urls')),
    path('blog/', include('blog.urls')),
    path('feedback/', include('feedback.urls')),
    path('about/', include('About.urls')),
    path('Guidelines/', include('Guidelines.urls')),
    path('Researchers/', include('Researchers.urls')),
    path('PublicationProject/', include('PublicationProject.urls')),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

About/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
  
class TeamMembers(models.Model):
    id=models.AutoField(primary_key=True)
    first_Name = models.CharField(max_length=100)
    last_Name = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to='team_members_pics/', blank=True)

    def clean(self):
        super().clean()
        if self.profile_pic and self.profile_pic.size > 2 * 1024 * 1024:
            raise ValidationError("Profile picture file size should be less than 2MB")

    
    current_job = models.CharField(max_length=100)
    work_experience = models.CharField(max_length=100)

    Role = models.CharField(max_length=100)


    uv_name = models.CharField(max_length=100)
    dept_name = models.CharField(max_length=100)
    domain_expertise=models.CharField(max_length=100)
  
 

    linekdin_url = models.URLField(blank=True)
    github_url = models.URLField(blank=True)
    personal_website = models.URLField(blank=True)
    google_scholar_url = models.URLField(blank=True)


   

    def __str__(self):
        return f"{self.first_Name} {self.last_Name}"

About/forms.py
from django import forms
from About.models import TeamMembers

class team_form_Details(forms.ModelForm):
    class Meta:
        model=TeamMembers
        fields= "__all__"

About/views.py
from django.shortcuts import render
from django.http import HttpResponse

from About.models import TeamMembers
from About import forms

# Create your views here.

def about_us(request):
    team_list=TeamMembers.objects.order_by('first_Name')
    # Researchers_list=researcher_form.objects.get(pk=researcher_id)
    diction={'title':'Home Page','team_list':team_list}
    return render(request, "about_us/about.html", context=diction)



def team_info_form(request):
    new_form = forms.team_form_Details()

    if request.method == 'POST':
        new_form = forms.team_form_Details(request.POST, request.FILES)

        if new_form.is_valid():
            new_form.save(commit=True)
            return about_us(request)
        else:
            print('ERROR FORM INVALID', new_form.errors)
    dict1 = {'test_form': new_form, 'heading': 'Add New teammate'}

    return render(request, 'about_us/teaminfo_form.html', context=dict1)



def edit_team_info(request, member_id):
    members_info = TeamMembers.objects.get(pk=member_id)
    form = forms.team_form_Details(instance=members_info)
    diction = {}
    if request.method == "POST":
        form = forms.team_form_Details(request.POST, request.FILES, instance=members_info)

        if form.is_valid():
            form.save(commit=True)
            # return researcher_view(request)
            diction.update({'sucess_text': 'Successfully Updated '})


    diction.update({'edit_form': form})
    diction.update({'member_id': member_id})

    return render(request, 'about_us/edit_team.html', context=diction)


# Delete Research_Member

def delete_info(request,member_id):
    team_member= TeamMembers.objects.get(pk=member_id).delete()
    diction={'delete_text':'Successfully Deleted !'}
    return render(request,'about_us/delete.html',context=diction)

templates/about_us/delete.html
<!DOCTYPE html>
 {% extends "base.html" %}
 {% block body_block %}
 {% load static %}

<div class="alert alert-danger"> {{delete_text}} </div>   
 
 {% endblock %}

templates/about_us/edit_team.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About SAFENET.AI{% endblock %}

{% block content %}


<div class="container">
    <div class="card">
        <div class="card-header">
            <h3 class="Header_title">Edit team Information</h3>
        </div>
        {% if sucess_text %}
        <div class="alert alert-success" role="alert">
            {{ sucess_text }}
        </div>
        {% endif %}

        <div class="card-body">
            <form enctype="multipart/form-data" method="POST">
                {{ edit_form.as_p }}
                <script>
                    document.addEventListener("DOMContentLoaded", function () {
                        var inputs = document.querySelectorAll("input");
                        inputs.forEach(function (input) {
                            input.classList.add("form-control");
                            input.setAttribute("placeholder", "Enter " + input.name);
                        });

                        var checkboxes = document.querySelectorAll("input[type='checkbox']");
                        checkboxes.forEach(function (checkbox) {
                            checkbox.classList.remove("form-control");
                        });
                    });
                </script>
                {% csrf_token %}
                <div class="d-flex justify-content-center" style="align-items: center; width: 100%;">
                    <button type="submit" class="btn btn-primary" style="width: 50%;">Update</button><br>
                </div>
          
                <div class="d-flex justify-content-end mt-2">
                    <a href="{% url 'About:delete_info' member_id=member_id %}" class="btn btn-danger"
                        onclick="return confirm('Delete This Member')">Delete</a>
                </div>
           
            </form><br>
        </div>
        {% csrf_token %}

        </form><br>

    </div>
 
</div>
</div>

{% endblock %}

templates/about_us/teaminfo_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About SAFENET.AI{% endblock %}

{% block content %}



<div class="container">
    <div class="card">
        <div class="card-header">
            <h3 class="Header_title">Submit Your Information</h3>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" method="POST">
                {{ test_form.as_p }}
                <script>
                    document.addEventListener("DOMContentLoaded", function() {
                        var inputs = document.querySelectorAll("input");
                        inputs.forEach(function(input) {
                            if (["linekdin_url", "github_url", "personal_website"].includes(input.name)) {
                                input.classList.add("form-control");
                            } else {
                                input.classList.add("form-control");
                                input.setAttribute("placeholder", "Enter " + input.name);
                            }
                        });
                    });
                </script>
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
               
    </div>
</div>




 {% endblock %}

templates/about_us/teaminfo_show.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About SAFENET.AI{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="{% static 'Researchers/info_show.css' %}" rel="stylesheet">


<section id="team" class="pb-5">
  <div class="container">
    <h5 class="section-title h1">Team member</h5>
    <div class="row">
      {% for member in team_list|dictsort:"id"  %}
      <!-- Team Member -->
      <div class="col-12 col-sm-6 col-md-4">
        <div class="image-flip">
          <div class="mainflip flip-0">
            <!-- Front Side -->
            <div class="frontside">
              <div class="card">
                <div class="card-body text-center">
                  <p>
                    <img class="img-fluid" src="{% if member.profile_pic %}{{ member.profile_pic.url }}{% else %}{% static 'images/default_profile.png' %}{% endif %}" alt="card image">
                  </p>
                  <h4 class="card-title">{{ member.first_Name }} {{member.last_Name}} </h4>
                  <p class="card-text">
                    <strong>Current job:</strong> {{ member.current_job }}
                  </p>

                  <p class="card-text">
                    <strong>work_experience:</strong> {{ member.work_experience }}
                  </p>
                  <p class="card-text">
                    <strong>Role:</strong> {{ member.Role }}
                  </p>

                  <!-- <p> <i class="fa fa-user"></i></p> -->
                </div>
           
              </div>

            </div>
            <!-- Back Side -->
            <div class="backside">
              <div class="card">
             
                <div class="card-body text-center mt-4">
                  
                    <h5 class="card-title">  {{ member.first_Name }} {{member.last_Name}} </h5>

                    <p class="card-text">
                    <strong>University:</strong> {{ member.uv_name }}<br>
                    <strong>Department:</strong> {{ member.dept_name }}<br>
                    <strong>Domain_expertise:</strong> {{ member.domain_expertise }}<br>
           
                  </p>
                  <p>
<!--               
                    <a href="{{ researcher.github_url }}" class="social_icons"> <i class="fa fa-github"></i></a>
                    <a href="{{ researcher.personal_site_url }}" class="social_icons"> <i class="fa fa-globe"></i></a>
                    <a href="{{ researcher.linekdin_url }}" class="social_icons"> <i class="fa fa-linkedin"></i></a> -->
                    {% if member.github_url %}
                    <a href="{{ researcher.github_url }}" target="_blank" class="social_icons"> <i class="fa fa-github"></i></a>
                    {% endif %}
  
                    {% if member.personal_website %}
                    <a href="{{ member.personal_website }}" target="_blank" class="social_icons"> <i class="fa fa-globe"></i></a>
                    {% endif %}
  
                    {% if member.linekdin_url %}
                    <a href="{{ member.linekdin_url }}" target="_blank" class="social_icons"> <i class="fa fa-linkedin"></i></a>
                    {% endif %}
                  
             
                    
                    {% if member.google_scholar_url %}
                    <a href="{{ researcher.google_scholar_url }}" target="_blank" class="social_icons"> <i class="fa fa-graduation-cap"></i></a>
                    {% endif %}

                  </p>

                  

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

      <!-- Add Member Card -->
   
      <div class="col-12 col-sm-6 col-md-4">
        <div class="image-flip1">
          <div class="mainflip flip-0">
        <div class="frontside">
          <div class="card">
        <div class="card-body text-center">
          <p>
        <img class="img-fluid" src="/static/images/add_icon.png" alt="Add Member">
          </p>
          <!-- <h4 class="card-title">Add New Member</h4> -->
          <p class="card-text"></p>
        <a href="{% url 'About:team_info_form' %}" class="btn btn-primary">Add New Team Member</a>
          </p>

         
        </div>
          </div>
        </div>
          </div>
        </div>
      </div>



    </div>
  </div>
</section>


{% endblock %}
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->