Guidelines/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf.urls.static import static


app_name = 'Guidelines'

urlpatterns = [
    
    path('guidelines_cards/', views.guidelines_cards, name='guidelines_cards'),
    path('ai/', views.ai, name='ai'),
    path('data_analytics/', views.data_analytics, name='data_analytics'),
    path('data_engineer/', views.data_engineer, name='data_engineer'),
    path('research/', views.research, name='research'),
  
]

urlpatterns+= staticfiles_urlpatterns()
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('my-posts/', views.my_blog_posts, name='my_blog_posts'),
    path('approval/', views.blog_approval_list, name='blog_approval_list'),
    path('approve/<int:pk>/', views.blog_approve, name='blog_approve'),
    path('like/<int:pk>/', views.like_blog_post, name='like_blog_post'),
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/edit/', views.blog_edit, name='blog_edit'),
    path('<slug:slug>/delete/', views.blog_delete, name='blog_delete'),
]

safenet_ai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('research/', include('research_papers.urls')),
    path('expert-topics/', include('expert_topics.urls')),
    path('blog/', include('blog.urls')),
    path('feedback/', include('feedback.urls')),
    path('about/', include('About.urls')),
    path('Guidelines/', include('Guidelines.urls')),
    path('Researchers/', include('Researchers.urls')),
    path('PublicationProject/', include('PublicationProject.urls')),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Guidelines/models.py
from django.db import models

# Create your models here.

Guidelines/views.py
from django.shortcuts import render

# Create your views here.

def guidelines_cards(request):
    return render (request, 'guidelines/index.html',context= {})


def ai(request):
    return render (request, 'guidelines/ai_ml.html',context= {})


def data_analytics(request):
    return render (request, 'guidelines/data_analytics.html',context= {})

def data_engineer(request):
    return render (request, 'guidelines/data_engineering.html',context= {})


def research(request):
    return render (request, 'guidelines/academic_research.html',context= {})

templates/guidelines/old/gudielines_cards.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
{% load static %}
<style>
    body {
        font-family: 'Open Sans', sans-serif;
        background-color: rgb(252, 252, 252);
        background-image: url('{% static "images/background.jpg" %}'); /* Updated background image */
        background-size: cover; /* Ensures the image covers the entire background */
        background-position: center;
    }

    h1 {
        color: #fff;
    }

    .lead {
        color: #aaa;
    }

    .wrapper {
        margin: 10vh;
    }

    .card {
        border: none;
        transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
        overflow: hidden;
        border-radius: 20px;
        min-height: 450px;
        box-shadow: 0 0 12px 0 rgba(0, 0, 0, 0.2);
    }

    @media (max-width: 768px) {
        .card {
            min-height: 350px;
        }
    }

    @media (max-width: 420px) {
        .card {
            min-height: 300px;
        }
    }

    .card-has-bg {
        background-size: 120%;
        background-repeat: no-repeat;
        background-position: center center;
    }

    .card-has-bg:before {
        content: '';
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: inherit;
        filter: grayscale(100%);
    }

    .card-has-bg:hover:before {
        filter: grayscale(0%); /* Remove grayscale filter on hover */
    }

    .card-has-bg:hover {
        transform: scale(0.98);
        box-shadow: 0 0 5px -2px rgba(0, 0, 0, 0.3);
        background-size: 130%;
    }

    .card-footer {
        background: none;
        border-top: none;
    }

    .card-footer .media img {
        border: solid 3px rgba(255, 255, 255, 0.3);
    }

    .card-title {
        font-weight: 800;
    }

    .card-meta {
        color: rgba(0, 0, 0, 0.3);
        text-transform: uppercase;
        font-weight: 500;
        letter-spacing: 2px;
    }

    .card-body {
        transition: all 500ms cubic-bezier(0.19, 1, 0.22, 1);
    }

    .card:hover .card-body {
        margin-top: 30px;
        transition: all 800ms cubic-bezier(0.19, 1, 0.22, 1);
    }

    .card-img-overlay {
        transition: all 800ms cubic-bezier(0.19, 1, 0.22, 1);

    }

.ai_eng{
    background-image:url('{% static "images/AI_guide.jpg" %}');
}
    /*

new code */
</style>
<div class="container-fluid row bannar_body d-flex align-items-center justify-content-center text-center" style="background-image: url('{% static 'images/5zati5qk.png' %}'); background-size: cover; background-position: center; height: 200px;">
    <div class="bannar_items" id="main_about" style="background: transparent;">
        <h1 class="w-100" style="font-family: 'Overpass', sans-serif; color: white; text-shadow: 2px 2px 4px #000000; text-decoration: underline; font-weight: bold;">Guidelines
        </h1>
    </div>
</div>
<div class="container-fluid">

    <section class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 mb-4">
                    
                    <a {% if user.is_authenticated %} href="{% url 'Guidelines:ai' %}" 
                    {% else %} href="{% url 'login_app:login_page' %}" title="Log in to access AI content"
                    {% endif %}>
                
                    <div class="card text-dark card-has-bg click-col ai_eng" 
                    style="min-height: 300px; background-size: cover; background-position: center;">
                    <img class="card-img d-none" src="https://source.unsplash.com/600x900/?ai" alt="AI">
                    <div class="card-img-overlay d-flex flex-column">
                        <div class="card-body">
                            <small class="card-meta mb-2">A Complete Guideline to</small>
                           
                            <small><i class="far fa-clock"></i> Click to Explore</small>
                        </div>
                        <div class="card-footer">
                            <div class="media">
                                <img class="mr-3 rounded-circle" src="{% static 'images/logo.png' %}"
                                    alt="Generic placeholder image" style="max-width:50px">
                                <div class="media-body">
                                    <h6 class="my-0 text-dark d-block" style="padding-top: 15px;">SafeNet AI</h6>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                </a>
                   
                </div>
                <!-- .....data old -->
                <div class="col-sm-12 col-md-6 mb-4">
                    <a {% if user.is_authenticated %} href="{% url 'Guidelines:data_analytics' %}" 
                    {% else %} href="{% url 'login_app:login_page' %}" title="Log in to access AI content"
                    {% endif %}>  
                    <div class="card text-dark card-has-bg click-col"
                    style="background-image:url('{% static "images/DA_Guide.jpg" %}'); min-height: 300px; background-size: cover; background-position: center;">
                        <img class="card-img d-none" src="https://source.unsplash.com/600x900/?data"
                            alt="Data Analytics">
                        <div class="card-img-overlay d-flex flex-column">
                            <div class="card-body">



                                <small class="card-meta mb-2">A Complete Guideline to</small>
                                
                                <small><i class="far fa-clock"></i> Click to Explore</small>
                            </div>
                            <div class="card-footer">
                                <div class="media">
                                    <img class="mr-3 rounded-circle" src="{% static 'images/logo.png' %}"
                                        alt="Generic placeholder image"style="max-width:50px">
                                    <div class="media-body">
                                        <h6 class="my-0 text-dark d-block"style="padding-top: 15px;">SafeNet AI</h6>
                                        <!-- <small>Director of UI/UX</small> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                
                </a>
                  
                </div>


                <!-- data old -->

                <div class="col-sm-12 col-md-6 mb-4">
                    <a {% if user.is_authenticated %} href="{% url 'Guidelines:data_engineer' %}" 
                    {% else %} href="{% url 'login_app:login_page' %}" title="Log in to access AI content"
                    {% endif %}>  
                    <div class="card text-dark card-has-bg click-col"
                    style="background-image:url('{% static "images/DE.jpg" %}'); min-height: 300px; background-size: cover; background-position: center;">
                    <img class="card-img d-none" src="{% static 'images/DE.jpg' %}"
                        alt="Data Engineer">
                    <div class="card-img-overlay d-flex flex-column">
                        <div class="card-body">


                            <small class="card-meta mb-2">A complete Guide to</small>
                            
                            <small><i class="far fa-clock"></i> Click TO Explore</small>
                        </div>
                        <div class="card-footer">
                            <div class="media">
                                <img class="mr-3 rounded-circle" src="{% static 'images/logo.png' %}"
                                    alt="Generic placeholder image"style="max-width:50px">
                                <div class="media-body">
                                    <h6 class="my-0 text-dark d-block"style="padding-top: 15px;">SafeNet AI</h6>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                    </a>
                    
                </div>
                <div class="col-sm-12 col-md-6 mb-4">
                    <a {% if user.is_authenticated %} href="{% url 'Guidelines:research' %}" 
                    {% else %} href="{% url 'login_app:login_page' %}" title="Log in to access AI content"
                    {% endif %}> 
                    <div class="card text-dark card-has-bg click-col"
                    style="background-image:url('{% static 'images/AR.jpg' %}'); min-height: 300px; background-size: cover; background-position: center;">
                    <img class="card-img d-none" src="{% static 'images/AR.jpg' %}" alt="Research">
                    <div class="card-img-overlay d-flex flex-column">
                        <div class="card-body">

                            <small class="card-meta mb-2">A complete guide to </small>
                            
                            <small><i class="far fa-clock"></i> Click to Explore</small>
                        </div>
                        <div class="card-footer">
                            <div class="media">
                                <img class="mr-3 rounded-circle" src="{% static 'images/logo.png' %}"
                                    alt="Generic placeholder image" style="max-width:50px">

                                <div class="media-body">
                                    <h6 class="my-0 text-dark d-block" style="padding-top: 15px;">SafeNet AI</h6>

                                </div>
                            </div>
                        </div>
                    </div>
                </div></a>
                   
                </div>
            </div>
        </div>

</div>

</section>

</div>

{% endblock %}